service: dynamodb-perf-testing-consistency

plugins:
  - serverless-python-requirements

provider:
  lambdaHashingVersion: "20201221"
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:DescribeTable"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:Query"
          Resource: 
            - !GetAtt TestTable.Arn
            - Fn::Join: 
              - "/"
              - - Fn::GetAtt:
                  - TestTable 
                  - Arn
                - "index/GSI1"
  environment:
    TABLE_NAME: !Ref TestTable

functions:
  mainTable:
    handler: main_table.handler
  gsi:
    handler: gsi.handler

resources:
  Resources:
    TestTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: 'Id'
            AttributeType: 'S'
          - AttributeName: 'GSIPK'
            AttributeType: 'S'
        KeySchema: 
          - AttributeName: 'Id'
            KeyType: 'HASH'
        BillingMode: 'PAY_PER_REQUEST'
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName:  GSIPK
                KeyType: HASH
            Projection: 
              ProjectionType: ALL